# Kafka and Zookeeper

FROM antlypls/spark:1.5.1

# Install Kafka-python in the correct runtime environment to be used/replicated as needed
RUN yum install -y zip
RUN yum install -y python-setuptools
RUN easy_install pip
RUN pip install kafka-python

#RUN zip -r kafka-python.zip /usr/lib/python2.6/site-packages/kafka
